### ISSUE TITLE
Document uninstallation

### ISSUE THREAD

**Issue by scaleoutsean** [NetApp/netappdvp#101]
Plugin uninstallation is not documented. Can it be added?

There are two ways to install, so if one wants to switch from one to another, I suppose it's reasonable to need these steps.

Edit: one reason why I created this issue is that sometimes plugin uninstall doesn't work properly and a host reboot is required (probably a Docker issue, but later we can debug it or document that a reboot is required).

**Comment by miguelgm** [comment]
It would be great to also add an upgrade procedure if there is other than uninstall and install the new version.

**Comment by adkerr** [comment]
Moved to netapp/trident#83
