### ISSUE TITLE
E-Series support with Embedded API systems

### ISSUE THREAD

**Issue by plz** [NetApp/netappdvp#104]
[Current docs](http://netappdvp.readthedocs.io/en/latest/install/ndvp_e_config.html#example-e-series-config-file) have references to systems running behind the E-Series rest proxy, but are systems running the Embedded System Manager(like e2800 family) also supported on netapp dvp?

If so, it would be good to have the documentation stating it, and also some of the configurations directives, make less sense or need to be named differently.

**Comment by adkerr** [comment]
@plz,

Yes, the embedded proxy is also supported. Will take an action to clarify the documentation.

**Comment by adkerr** [comment]
Moved to netapp/trident#84
