### ISSUE TITLE
Logical validation of values in config.json

### ISSUE THREAD

**Issue by scaleoutsean** [NetApp/netappdvp#105]
I came across this today, using `netapp:17.07` - it seems some values aren't sanity-checked - for example SVIP in the example below:

```
{
	"version": 1,
	"storageDriverName": "solidfire-san",
	"Endpoint": "https://admin:admin@192.168.160.3/json-rpc/7.0",
	"SVIP": " 10.0.0.7:3260",
	"TenantName": "docker",
	"InitiatorIFace": "default"
}
```
Clearly this is a valid JSON file, but the SVIP value is incorrect and results in some interesting problems down the road.

This is similar to #56.

**Comment by adkerr** [comment]
Moved to netapp/trident#85
