### ISSUE TITLE
401 (Unauthorized)

### ISSUE THREAD

**Issue by rosebude** [NetApp/netappdvp#106]
Hello, 
What's wrong with me...

Docker version 17.09.0-ce
NetApp Release 9.1P3

My config:

/etc/netappdvp/config.json 

> {
>     "version": 1,
>     "storageDriverName": "ontap-nas",
>     "managementLIF": "xxxx",
>     "dataLIF": "xxxx",
>     "svm": "CLUSTER_NAME",
>     "username": "admin",
>     "password": "admin_pass",
>     "aggregate": "aggr01"
> }

`docker plugin install --grant-all-permissions --alias netapp netapp/ndvp-plugin:17.07`

`journalctl -fu docker`
show me:
....
\" error=\"Problem while initializing: Could not determine Data ONTAP API version. 401 (Unauthorized)\"
....

I don't understand.... admin user have all the netapp role....

**Comment by rosebude** [comment]
@adkerr 
ssh managementLIF@username with admin_pass is ok

**Comment by rosebude** [comment]
Do you know URL to test netapp API ?

**Comment by ntap-rippy** [comment]
# send request
$ cat system-get-ontapi-version.xml 
<?xml version="1.0" encoding="UTF-8"?>
<netapp xmlns="http://www.netapp.com/filer/admin" version="1.21">
  <system-get-ontapi-version/>
</netapp>

# get response
$ curl -k -X POST -d @./system-get-ontapi-version.xml https://user:password@1.2.3.4/servlets/netapp.servlets.admin.XMLrequest_filer
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE netapp SYSTEM 'file:/etc/netapp_gx.dtd'>
<netapp version='1.100' xmlns='http://www.netapp.com/filer/admin'>
<results status="passed"><major-version>1</major-version><minor-version>100</minor-version></results></netapp>

**Comment by adkerr** [comment]
It's also possible that you don't have http/s management enabled in the cluster options which would disable zapi access but still allow ssh.

**Comment by rosebude** [comment]
ok thanks . 
It works.... Curl show me proxy setting probem.
Thanks you.
