### ISSUE TITLE
Using netappdvp as an API client

### ISSUE THREAD

**Issue by cdhunt** [NetApp/netappdvp#107]
I'm trying to use `netappdvp/api/ontap` as a client to potentially back a Terraform provider. Using `curl` against `https://user@pass:filer/servlets/netapp.servlets.admin.XMLrequest_filer` works fine, but the below always returns a 401 Unauthorized. Do you have any usage or debugging suggestions?

```go
c := ontap.DriverConfig{
    Username: "user",
    Password: "pass",
    ManagementLIF: "filer",
}

d := ontap.NewDriver(c)

response, err := d.VolumeList("")
```

**Comment by adkerr** [comment]
@cdhunt please note that ndvp is not intended to be used as a general purpose ONTAP api client and is not supported in such a capacity.

That said, you may try setting the “api” DebugTraceFlags setting to true when you initialize the driver and see if the extra debug info provides any insight.

**Comment by cdhunt** [comment]
Thanks, @adkerr. I saw you mention that in another issue. I'm testing out [go-netapp](https://github.com/pepabo/go-netapp). as a general purpose ontapi client.
