### ISSUE TITLE
Head  of line blocking creation of PV 

### ISSUE THREAD

**Issue by sureshvis** [NetApp/netappdvp#111]
Step 1 : created a PV (name: test1) with 5 MB,  trident warned with below error

Error creating volume. API status: failed, Reason: Size “5MB” (“5242880B”) is too small.  Minimum size is “20MB” (“20971520B”).   

Step 2: deleted the PV which was warning from step 1

Step 3:  created new PV with 1GB request (with new PV name: test2), the trident would not create new PV but keep trying to create PV (name: test1) from step 1 in loop. 

when the PV was deleted, the corresponding object from trident is not geting cleared

**Comment by adkerr** [comment]
This is in the wrong repo, please open this in NetApp/trident
