### ISSUE TITLE
netapp.sock: no such file or directory

### ISSUE THREAD

**Issue by julianojfsj** [NetApp/netappdvp#112]
Hello, i have the same issue as stated by post #86 but as the OP's (Sattera) issue hasn't been resolved and i'm stuck with the same error i would like to "re-open" this case to try and solve this issue.

I have Docker v17.06.0-ce running inside a Ubuntu Server v16.04.3 LTS and i tried to configure netappdvp using the Docker Managed Plugin Method as shown in this #[page](http://netappdvp.readthedocs.io/en/latest/install/host_config.html#host-configuration) and i get the same error. As can be seen in the following image:

![erro1](https://user-images.githubusercontent.com/19155592/34388196-7e2621ec-eb19-11e7-8eb1-79ee674178a2.PNG)

![erro2](https://user-images.githubusercontent.com/19155592/34388203-82cef1d8-eb19-11e7-9801-f8e296b12633.PNG)

I would like to be able to execute the command to enable debugging on to the netappdvp plugin but it is done just as it tries to enable the plugin and when i try to do that, i get the same error shown in the second image.

Here is my config file:
{
        "version": 1,
        "storageDriverName": "ontap-san",
        "managementLIF": "10.0.0.1",
        "dataLIF": "10.0.0.2",
        "svm": "SVM_Estudo",
        "username": "ndvp_user",
        "password": "*********",
        "aggregate": "aggr_01"
}

I also tried with ontap-nas as storageDriverName, no good.

Thank you in advance.

**Comment by clintonk** [comment]
Hello, @julianojfsj.  The error you see means the plugin didn't start.  Please follow the troubleshooting steps outlined here and report back:  http://netappdvp.readthedocs.io/en/latest/support.html

**Comment by julianojfsj** [comment]
Did the steps mentioned, got the same result, as shown on the image below.

![image](https://user-images.githubusercontent.com/19155592/34523083-0bd1ff76-f07d-11e7-88a4-bec28cf436ef.png)

**Comment by clintonk** [comment]
@julianojfsj We don't understand why you aren't seeing any log messages from the plugin.  I suggest you try running netappdvp as a binary to see what errors it might be logging.  Just grab the latest release from GitHub, unpack the binary, and run it.  You'll need to use sudo (or run as root), and specify the config and debug parameters, i.e.:

`sudo ./netappdvp --config /etc/netappdvp/config.json --debug`

**Comment by julianojfsj** [comment]
I downloaded netappdvp through the wget function but i still think it did the same as if i would download from Github, anyways i executed that command with debug on and here is the output.

![image](https://user-images.githubusercontent.com/19155592/34610016-57e22ac8-f206-11e7-821f-9443c9478417.png)

**Comment by adkerr** [comment]
Alright, now we have a cause 😄 
It looks like you are supplying improper login credentials for the storage array, make sure you have the right username/password in your config file. If using a svm-scoped user, make sure you're pointing to the svm management LIF, if using a cluster-scoped user make sure you're pointing at the cluster management LIF.

**Comment by clintonk** [comment]
Thanks @julianojfsj.  Looks like you've got incorrect or missing credentials in the config file.  Can you check that, please?

**Comment by julianojfsj** [comment]
I did check it with the Storage people, and all seems good on their side. I am using the same credentials they determined for the SVM i am using, i even watched the guy do it on his screen. As kind of a side note, i would also like to provide this image, which shows that when i try to perform the Traditional Install Method, i follow the steps provided on the guide and when i perform the 4th step, i get this message:

![image](https://user-images.githubusercontent.com/19155592/34684827-8c11bca8-f48d-11e7-9300-1564078e8b7d.png)

**Comment by adkerr** [comment]
Closing this pending update. If this needs to be reopened, please open in NetApp/Trident repo.
