### ISSUE TITLE
Is there an ExportPolicyGet function？

### ISSUE THREAD

**Issue by keontang** [NetApp/netappdvp#113]
I just only found ExportPolicyCreate func.
If an ExportPolicy exists, I call ExportPolicyCreate, what will i get, an error?

**Comment by keontang** [comment]
And I cann't find: export-rule-destroy.go, export-rule-get.go, export-policy-destroy.go, export-policy-get.go

**Comment by clintonk** [comment]
Hello, keontang.  The netappdvp code only contains Go bindings for ONTAP APIs that it needs.  It isn't meant as a general purpose SDK, sorry!

**Comment by keontang** [comment]
Because i want to use these apis to do policies in my program @clintonk
