### ISSUE TITLE
Plugin not found

### ISSUE THREAD

**Issue by tbouvet** [NetApp/netappdvp#114]
Since I have installed ndvp plugin, an error message appears in the docker daemon log : 
```
Jan 03 14:29:24 host1 dockerd[3284]: time="2018-01-03T14:29:24.420038033+01:00" level=error msg="plugin not found"
Jan 03 14:29:13 host1 dockerd[3284]: time="2018-01-03T14:29:13.164583309+01:00" level=error msg="plugin not found"
```
_But the netapp plugin seems to be ok because I can create a volume and use it in a container_.

**docker version:**
```
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:24:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:23:00 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
**OS:**
Ubuntu 16.04.LTS

**My netapp.conf:**
```
{
  "version": 1,
  "storageDriverName": "ontap-nas",
  "managementLIF": "xx.xx.xx.xx",
  "dataLIF": "yy.yy.yy.yy",
  "svm": "host2",
  "username": "docker",
  "password": "mypassword",
  "aggregate": "aggr_HOST2_sata_01",
  "storagePrefix": "ndvp_"
}

```
Does everybody have an idea please ?

**Comment by adkerr** [comment]
I have seen this behavior sometimes as well. As best as I can tell it seems to be come about from docker's internal caching mechanisms around plugins and which volumes belong to them; since I normally see this after I have attempted to reinstall the plugin for some reason.

**Comment by adkerr** [comment]
Forgot to mention that I believe this to be a benign warning emitted from the docker engine. I do not think there is much we can do from the plugin side to prevent it.

**Comment by tbouvet** [comment]
I have installed the plugin on different machines and I always have this message on each machine.
This message appears a lot of times (about 4/5 times per minute). Here is an extract for 5 minutes : 
```
Jan 03 16:46:22 host1 dockerd[3284]: time="2018-01-03T16:46:22.471820443+01:00" level=error msg="plugin not found"
Jan 03 16:45:57 host1 dockerd[3284]: time="2018-01-03T16:45:57.528764692+01:00" level=error msg="plugin not found"
Jan 03 16:45:50 host1 dockerd[3284]: time="2018-01-03T16:45:50.650374597+01:00" level=error msg="plugin not found"
Jan 03 16:45:34 host1 dockerd[3284]: time="2018-01-03T16:45:34.432611228+01:00" level=error msg="plugin not found"
Jan 03 16:45:02 host1 dockerd[3284]: time="2018-01-03T16:45:02.557175148+01:00" level=error msg="plugin not found"
Jan 03 16:44:59 host1 dockerd[3284]: time="2018-01-03T16:44:59.556328081+01:00" level=error msg="plugin not found"
Jan 03 16:44:47 host1 dockerd[3284]: time="2018-01-03T16:44:47.643749884+01:00" level=error msg="plugin not found"
Jan 03 16:44:19 host1 dockerd[3284]: time="2018-01-03T16:44:19.964988443+01:00" level=error msg="plugin not found"
Jan 03 16:44:12 host1 dockerd[3284]: time="2018-01-03T16:44:12.128351603+01:00" level=error msg="plugin not found"
Jan 03 16:43:59 host1 dockerd[3284]: time="2018-01-03T16:43:59.065848071+01:00" level=error msg="plugin not found"
Jan 03 16:43:35 host1 dockerd[3284]: time="2018-01-03T16:43:35.140030344+01:00" level=error msg="plugin not found"
Jan 03 16:43:32 host1 dockerd[3284]: time="2018-01-03T16:43:32.324392157+01:00" level=error msg="plugin not found"
Jan 03 16:43:05 host1 dockerd[3284]: time="2018-01-03T16:43:05.577826265+01:00" level=error msg="plugin not found"
Jan 03 16:42:56 host1 dockerd[3284]: time="2018-01-03T16:42:56.776031481+01:00" level=error msg="plugin not found"
Jan 03 16:42:33 host1 dockerd[3284]: time="2018-01-03T16:42:33.033389932+01:00" level=error msg="plugin not found"
Jan 03 16:42:19 host1 dockerd[3284]: time="2018-01-03T16:42:19.864933145+01:00" level=error msg="plugin not found"
Jan 03 16:42:19 host1 dockerd[3284]: time="2018-01-03T16:42:19.543770166+01:00" level=error msg="plugin not found"
Jan 03 16:41:59 host1 dockerd[3284]: time="2018-01-03T16:41:59.324988263+01:00" level=error msg="plugin not found"
Jan 03 16:41:39 host1 dockerd[3284]: time="2018-01-03T16:41:39.714932308+01:00" level=error msg="plugin not found"
Jan 03 16:41:20 host1 dockerd[3284]: time="2018-01-03T16:41:20.649832979+01:00" level=error msg="plugin not found"
Jan 03 16:41:19 host1 dockerd[3284]: time="2018-01-03T16:41:19.852961883+01:00" level=error msg="plugin not found"
```

Any idea to stop it ?

**Comment by adkerr** [comment]
@tbouvet I'm not sure why this would appear on new installations, but it can appear if you have reinstalled the plugin after using it. Docker keeps a UUID of each plugin and associates that ID with the volumes the plugin creates. If you reinstall the plugin then it gets a new ID but doesn't update the existing volumes to point to it. It then thinks there should be a plugin with the old UUID but can't find it.

You may want to contact Docker if you're seeing this on clean installations and also to see if there is a way to clean it up after-the-fact. A way to avoid this during version upgrades is to use the [`docker plugin upgrade`](https://docs.docker.com/engine/reference/commandline/plugin_upgrade/) command instead of doing a remove/install. That will keep the UUID correct.

**Comment by tbouvet** [comment]
Ok I understand.
But I have done a test : I have removed the plugin (and check no volumes use it) and the message has disappeared. And then when I install again, the message appears again.

**Comment by clintonk** [comment]
@tbouvet Have you tried restarting Docker to clear its internal cache?  There was a recent [discussion](https://github.com/moby/moby/issues/34545) about the plugin upgrade process.  You might try asking your question in the same forum.

**Comment by tbouvet** [comment]
@clintonk Yes I have tried restarting docker but the error message continue again.

**Comment by RemyCH** [comment]
We managed to remove the message by linking : 

@adkerr  

/var/run/docker/plugins/netapp.sock -> /var/run/docker/plugins/654321AZEZEDZdD.../netapp.sock

 Then the engine finally stop complaining about "plugin not found". But you have new issue, such as seeing volume in double. So it's not something you should do, but it looks like the engine is waiting for a default socket location in the plugins directory.

**Comment by tbouvet** [comment]
@adkerr I just install the plugin for the 1st time on a new docker host and I have the same error.

docker version : 
```
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:11:19 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:09:53 2017
  OS/Arch:      linux/amd64
  Experimental: false
```

**Comment by ntap-rippy** [comment]
See also:  https://github.com/moby/moby/issues/35992

**Comment by ntap-rippy** [comment]
This appears to be an upstream Docker bug, not an nDVP specific bug.  I was able to reproduce with Docker's vieux/sshfs example plugin.

Let's track the resolution of this over there.  We can re-open this if there's anything we need to do, but right now, there's nothing we can do about this.
