### ISSUE TITLE
plugin volume not found on inspect or rm

### ISSUE THREAD

**Issue by RemyCH** [NetApp/netappdvp#115]
Hello,

 We use your plugin on different dockerEE clusters with different configurations  : 
UCP 2.1.5
Docker engine 17.03
Plugin : 17.07

UCP 2.2.4
Docker engine 17.06
Plugin : 17.07

UCP 2.2.4
Docker engine 17.06
Plugin : 17.10.0

UCP 2.2.5 (release candidate)
Docker engine 17.06
Plugin : 17.10.1

 It seems like we have systematically the below issue with your plugin (any version 17.07, 17.10.0, 17.10.1) under 17.06/UCP 2.2.X.

 Here is the issue : 
 Using admin user, or lambda users, we can create a volume. Then we see the volume via "docker volume ls"
 But using bundle, or UI, we can't inspect or remove this volume. It returns a "volume not found".

- manually via bundle : 
```ruby
bash-4.2$ docker volume ls |grep remytest
netapp:latest       remytest
netapp:latest       remytest
netapp:latest       remytest
netapp:latest       remytest
netapp:latest       remytest
netapp:latest       remytest
netapp:latest       remytest
bash-4.2$ docker volume inspect remytest
[]
Error: No such volume: remytest
bash-4.2$
```

- via UI : 
![about to delete](https://user-images.githubusercontent.com/17552457/34775752-8b9d8d28-f614-11e7-9e1e-e23f773ed62d.png)
![no such volume](https://user-images.githubusercontent.com/17552457/34775770-95f21708-f614-11e7-82b3-a47d8631a989.png)

 We can inspect the volume without using the ucp bundle.
 Informations about my volume in /var/lib/docker/volumes/metadata.db are there : 

strings metadata.db |grep remytest
remytest{"Name":"remytest","Driver":"netapp:latest","Labels":{"com.docker.swarm.whitelists":"[\"node==dckdevdck181\"]","com.docker.ucp.access.label":"/Node/Workload/TEAM-DEV/mydev","com.docker.ucp.collection":"6ea02707-e2ff-4a3a-bfac-39464570cd73","com.docker.ucp.collection.6ea02707-e2ff-4a3a-bfac-39464570cd73":"true","com.docker.ucp.collection.95227568-0f22-42bd-a90d-b331de8097aa":"true","com.docker.ucp.collection.af70838e-f5d8-4a79-92e2-c2400d3e5b82":"true","com.docker.ucp.collection.b5a19ceb-6b67-485e-a250-2988585ba7e5":"true","com.docker.ucp.collection.root":"true","com.docker.ucp.collection.swarm":"true"},"Options":{}}

 It turned the plugin in debug mode, but when we inspect the volume : it returns strictly nothing in docker engine, or netapp plugin logs.

 Do you have any idea?

Thx
Remy

**Comment by kcrawley** [comment]
we've observed this behavior as well. the only workarounds we've found is to open a shell session to a manager node to remove the volume, or running a container on the manager node with access to the host docker socket.

**Comment by RemyCH** [comment]
Docker should fix it soon. I just checked.
So i close there.

**Comment by lordgnu** [comment]
Can you please leave a link to what you were looking at in the comments?  This issues affects me several times a week...

**Comment by adkerr** [comment]
@RemyCH I too would like to know where you found this confirmation, thanks!

**Comment by RemyCH** [comment]
Internal case @docker.
