### ISSUE TITLE
Feature Request: Resize NFS Volume's with nDVP

### ISSUE THREAD

**Issue by sim-heg** [NetApp/netappdvp#116]
Not sure if it is even compatible with the docker volume API but it would be nice if it would be possible to re-size (NFS) volumes with the nDVP.

Could look like this:
docker volume create -d netapp --name vol1 -o size=50g

docker volume create -d netapp --name vol1 -o resize=100g

**Comment by clintonk** [comment]
Hello, Simon.  We agree in principle with adding the ability to resize Docker volumes, but I think we're limited by the Docker volume API.  A Docker volume plugin has multiple entry points, and during a volume creation workflow the Docker engine calls Get before calling Create.  If Get succeeds, then the volume already exists and it won't call Create.  So I don't see how to make this work without a new Docker volume command.

Note that another community member [proposed](https://github.com/moby/moby/pull/30109) the ability to modify volumes including the size, and Docker ultimately didn't accept it.  Similarly, we [proposed](https://github.com/moby/moby/issues/33782) adding snapshots/clones, and despite overwhelming community support the Docker folks have not agreed to accept that, either.  I'd love to be wrong, but at this point I would be skeptical about seeing any significant improvements to the Docker volume facility.
