### ISSUE TITLE
Docker Plugin can't enable. 

### ISSUE THREAD

**Issue by Cuixn** [NetApp/netappdvp#119]
Follow Trident guide to deploy docker plugin. Can't enable the plugin.

CentOS7, Docker17.12, connect SF, test iscsi login is ok, checked config.json file(sf login and password), try to append config=/etc/trident/config.json or config=/etc/netappdvp/config.json, try to debug=true. still do not work. 

[root@vm01 plugins]# docker plugin install netapp/trident-plugin:18.01 --alias netapp --grant-all-permissions
18.01: Pulling from netapp/trident-plugin
88c0023f068a: Download complete
Digest: sha256:306c6dcb4c6e822f2db85c7ed2f73bb5254e4cdb4f14fa36e629451f70a35055
Status: Downloaded newer image for netapp/trident-plugin:18.01
Error response from daemon: dial unix /run/docker/plugins/9936afce1683e7609c61375c201e6bc8f903788c39f6d0116b9e70620eb054b4/netapp.sock: connect: no such file or directory

[root@vm01 netappdvp]# docker plugin list
ID                  NAME                DESCRIPTION                             ENABLED
9936afce1683        netapp:latest       Trident - NetApp Docker Volume Plugin   false

**Comment by Cuixn** [comment]
[root@vm01 netappdvp]# cat /etc/trident/config.json
{
    "version": 1,
    "storageDriverName": "solidfire-san",
    "Endpoint": "https://admin:Root1234@10.128.61.66/json-rpc/10.0",
    "SVIP": "10.128.61.67:3260",
    "TenantName": "docker”,

"InitiatorIFace": "default",
"Types": [
    {
        "Type": "docker-default",
        "Qos": {
            "minIOPS": 1000,
            "maxIOPS": 2000,
            "burstIOPS": 4000
}},
    {
        "Type": "docker-app",
        "Qos": {
            "minIOPS": 4000,
            "maxIOPS": 6000,
            "burstIOPS": 8000
}},
    {
        "Type": "docker-db",
        "Qos": {
            "minIOPS": 6000,
            "maxIOPS": 8000,
            "burstIOPS": 10000
}}
]}

**Comment by ntap-rippy** [comment]
The config file must live in the **/etc/netappdvp** directory and you should specify just the filename (not the path).

Relevant portion of docs: https://netapp-trident.readthedocs.io/en/stable-v18.01/docker/install/host_config.html#docker-managed-plugin-method-docker-1-13-17-03

> **config** - Specify the configuration file the plugin will use. **Only the file name should be specified**, e.g. gold.json, the location must be **/etc/netappdvp** on the host system. The default is config.json.

Relevant bit of code from the plugin:
https://github.com/NetApp/trident/blob/master/contrib/docker/plugin/container-launch.sh#L27-L31
```bash
# process config
MY_CONFIG=${config:-/etc/netappdvp/config.json}
basefile=$(basename ${MY_CONFIG})
MY_CONFIG="/etc/netappdvp/${basefile}"
export CONFIG_SWITCH="--config=${MY_CONFIG}"
```
