### ISSUE TITLE
Bug in ConvertSizeToBytes and ConvertSizeToBytes64 methods in utils/utils.go

### ISSUE THREAD

**Issue by kangarlou** [NetApp/netappdvp#13]
Because "b" is a suffix of "kb", "mb", "gb", etc., the conversion methods match with "b" before matching with the correct suffix. One quick fix is to remove [lookupTable["b"] = 0](https://github.com/NetApp/netappdvp/blob/master/utils/utils.go#L15l).

**Comment by lmprice** [comment]
@kangarlou I'm working on a fix for this right now.
