### ISSUE TITLE
Volume Mount Fails

### ISSUE THREAD

**Issue by dburkland** [NetApp/netappdvp#2]
I am trying to setup netappdvp on a CentOS 7.x container host running Docker 1.11.1 and keep getting the same error when I try to spin up a new container & netapp volume:

# docker run --rm -it --volume-driver netapp --volume test2:/my_vol nginx
docker: Error response from daemon: VolumeDriver.Mount: Problem attaching docker volume: netappdvp_test2 mountpoint: /var/lib/docker-volumes/netapp/netappdvp_test2 error: Problem mounting volume: netappdvp_test2 mountpoint: /var/lib/docker-volumes/netapp/netappdvp_test2 error: exit status 32.

I have verified the connection to the NetApp controller is sufficient as I am able to create volumes using the following command:

# docker volume create -d netapp --name test1
test1
# docker volume ls
DRIVER              VOLUME NAME
netapp              test
netapp              test1

FYI - The storage system I am trying to connect to is a FAS2220 running cDOT 8.3.2P1. Any help is greatly appreciated, thanks!

Dan

**Comment by innergy** [comment]
There's some good logging in /var/log/netappdvp.log that should steer you in the right direction. Drop it here if you're stuck!

**Comment by jaredhocutt** [comment]
If you're using NFS, a good place to start looking is to check if your export policy is configured to allow your host to mount the volume that was created.

**Comment by innergy** [comment]
Any luck? Let us know!

**Comment by dburkland** [comment]
Haven’t had a chance to re-test, will try again this week.

Thanks for the follow up replies!

Dan

**Comment by innergy** [comment]
Haven't heard from you in a bit, so we'll close for now. Let us know if you're still having issues.

**Comment by fxue** [comment]
bumping into the same issue. If I create clone with cloud ontap interface, docker is able to connect fine. But when I create via the REST API, job is COMPLETE. 
<status>COMPLETED</status>

I get:
docker: Error response from daemon: VolumeDriver.Mount: Problem attaching docker volume: clone6789 mountpoint: /var/lib/docker-volumes/netapp/clone6789 error: Problem mounting volume: clone6789 mountpoint: /var/lib/docker-volumes/netapp/clone6789 error: exit status 32.

Any pointers?

**Comment by fxue** [comment]
Found occm rest call has no problem while see mountpoint problem with ontap rest services.
i.e.
'http://*****/occm/api/vsa/volumes/VsaWorkingEnvironment-dmLTUV4e/svm_TeamTeamHack16Cardinals/cardinals/clone'

vs

curl 'https://****/api/1.0/ontap/volumes/d014ace2-6f03-11e6-8b3b-4d8e0894f7d7%3Atype%3Dvolume%2Cuuid%3D206b0cfe-c2a6-44d8-a1d2-b8a43f715b11/jobs/clone

**Comment by innergy** [comment]
Did you check out the log file? There will be a lot more detail in there. Look in /var/log/netappdvp. This error code is fairly generic, so please open a new issue with the relevant details from the log when you have them. Thanks!

**Comment by rushins** [comment]
i had the same issue ...does anyone have any solution.

docker: Error response from daemon: VolumeDriver.Mount: Problem attaching docker volume: netappdvp_ndvp_1 mountpoint: /var/lib/docker-volumes/netapp/netappdvp_ndvp_1 error: Problem mounting volume: netappdvp_ndvp_1 mountpoint: /var/lib/docker-volumes/netapp/netappdvp_ndvp_1 error: exit status 32.

**Comment by ntap-rippy** [comment]
@rushins SAN or NAS? Also, can you manually mount to this host from your NetApp system using your desired protocol?

**Comment by mcortinas** [comment]
I have the same problem , exit status 32 with NAS and volume is properly created in Netapp

the command:
```
# docker run --rm -it --volume-driver netapp --volume ndvp_2:/my_vol alpine ash                                            
docker: Error response from daemon: VolumeDriver.Mount: Problem attaching docker volume: netappdvp_ndvp_2 mountpoint: /var/lib/docker-volumes/netapp/netappdvp_ndvp_2 error: Problem mounting volume: netappdvp_ndvp_2 mountpoint: /var/lib/docker-volumes/netapp/netappdvp_ndvp_2 error: exit status 32.
```
the log output on /var/log/netappdvp/netapp.log
```
INFO[2017-03-22T16:32:42+01:00] Using storage driver: ontap-nas              
INFO[2017-03-22T16:32:42+01:00] Using config: {1 ontap-nas false map[] false [] []} 
INFO[2017-03-22T16:32:42+01:00] Starting docker volume plugin with the following options:  port= volume-driver=netapp volumeDir="/var/lib/docker-volumes/netapp"
ERRO[2017-03-22T16:33:45+01:00] Problem mounting volume: netappdvp_ndvp_2 mountpoint: /var/lib/docker-volumes/netapp/netappdvp_ndvp_2 error: exit status 32 
```

the environment
```
# docker --version
Docker version 1.11.2, build b9f10c9
# uname -a
Linux bcn1-server-232 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jacobjohnanda** [comment]
This should be because that there could be a conflicting trident volume that had been created during a previous installation.Please use the "storagePrefix"  in the backend file and this should resolve the issue

**Comment by zakkg3** [comment]
Faced this today.
Was trying to add the same backend into another K8s cluster.
Problem was:
 `Export rule does not exist for the client's IP or hostname`
Solved by:
added the hosts IP CDIR to the allowed ones and now it's working
