### ISSUE TITLE
permission denied when docker container tries to chown folder backed by ndvp made NFS volume

### ISSUE THREAD

**Issue by ragesaq** [NetApp/netappdvp#20]
Running docker 1.10 on Centos7 making the standard ELK docker container, hitting cdot 8.3.2. ndvp creates the volume fine and I can mount it on my Centos7 host. However, I get the following message when the container starts via the compose
elasticsearch_1  | chown: cannot read directory ‘/usr/share/elasticsearch/data/test’: Permission denied

I've banged my head on this for a while and I'm starting to think its an ndvp problem? 

Here is my relevant docker-compose.yml which I got most of the info from netapps pub post about it

version: '2'
services:
 elasticsearch:
   image: elasticsearch:latest
   command: elasticsearch -Des.network.host=0.0.0.0
   volumes:
     - elasticsearch_ndvp:/usr/share/elasticsearch/data/test

volumes:
  elasticsearch_ndvp:
    driver: netapp
    driver_opts:
      snapshotDir: "false"

Seems like I've got all the config points hit but I'm not sure if I'm missing anything

**Comment by ragesaq** [comment]
Found my issue, it was SELINUX on the host. Now to find out what needs to change to fix it.

**Comment by ragesaq** [comment]
@

**Comment by bnaylor** [comment]
Interesting, thanks for following up with the fix.  I did not know about :Z.

**Comment by ragesaq** [comment]
Ok, that wasn't all because I forgot I had run 'setenforce 0' which then let it through. I had to also run this: setsebool -P virt_use_nfs 1
This command is a persistent allow
