### ISSUE TITLE
Inform user of logfile location when we switch output to the logFile

### ISSUE THREAD

**Issue by ntap-rippy** [NetApp/netappdvp#33]
In **main.go** function **initLogging**, inform the user that all further output is going to the log file when we switch from logging to stdout to the log file:

`log.SetOutput(logFile)`

**Comment by lmprice** [comment]
Rippy, are you taking this one? Seems like an easy fix.

**Comment by dccurtis** [comment]
I was thinking of taking this next if its still up for grabs

**Comment by lmprice** [comment]
@dccurtis Go ahead and take this one.

**Comment by dccurtis** [comment]
This issue can be closed
