### ISSUE TITLE
RFE: Add support for SolidFire when using iSCSI multipath

### ISSUE THREAD

**Issue by dutchiechris** [NetApp/netappdvp#49]
Currently the ndvp supports host multipathing with ONTAP and E-Series but not SolidFire.  If you try to create a SolidFire backed volume and multipathing is enabled it errors out.  

Please add support for multipathing + SolidFire.

**Comment by adkerr** [comment]
Internally tracked by [US2228](https://rally1.rallydev.com/#/47479883219d/detail/userstory/91639296228)

**Comment by plz** [comment]
Is there a targeted release for this enhancement?

**Comment by innergy** [comment]
Not currently, but if it needs to be prioritized higher let us know.

**Comment by j-griffith** [comment]
I've submitted a PR to add multiattach to SF.  In the meantime, you can also add SF to the blacklisted devices in /etc/multipath.conf:

```
 blacklist {
     device {
         vendor  "SolidFir"
      }
  }
```
