### ISSUE TITLE
Licensing Question

### ISSUE THREAD

**Issue by erikh** [NetApp/netappdvp#5]
On the root of the project it says that you're Apache licensed, but in some of your files it says "Copyright Netapp, all rights reserved"

I'd love to support your filers in github.com/contiv/volplugin as well! Please let me know if I can somehow use your code to do this.

**Comment by innergy** [comment]
Cool! Unfortunately I am not a lawyer, and I can't play one in a GitHub issue. :) The copyright markup isn't that unusual in Apache licensed projects though. Come see us at our DockerCon booth to discuss.
