### ISSUE TITLE
RFE: nDVP with OnCommand API Services

### ISSUE THREAD

**Issue by mickeysh** [NetApp/netappdvp#65]
Today we require the Docker host to have direct 443 connectivity to the vServer to issue the ZAPI calls. For some of my customers I would be much better to work with APIS as a proxy, from a security perspective, and not open 443 to the vServer for every Docker host. 

Please consider adding API interface to the nDVP

**Comment by adkerr** [comment]
Internally tracked by [US2132](https://rally1.rallydev.com/#/47479883219d/detail/userstory/84417696012)
