### ISSUE TITLE
RFE: Ability to use more variables within the ontap-nas.json file

### ISSUE THREAD

**Issue by jamespohl** [NetApp/netappdvp#68]
Only a few variables are recognized within the .json file.

It would be nice to have the ability to specify some or all of the variables within

https://github.com/NetApp/netappdvp/blob/master/storage_drivers/ontap_nas.go#L158-L164

For example, we use namespaces, and we would have to manually specify the unixPermissions="---rwxrwxrwx" each time a volume is created.

as discussed in slack

**Comment by innergy** [comment]
Understood. This is on the roadmap.

**Comment by adkerr** [comment]
Internally tracked by [US2201](https://rally1.rallydev.com/#/47479883219d/detail/userstory/90428080320)

**Comment by innergy** [comment]
Fixed in 17.04.0
