### ISSUE TITLE
inconsistent specification of size and parsing of size

### ISSUE THREAD

**Issue by j-griffith** [NetApp/netappdvp#70]
Solidfire doesn't handle 'g' in size; looks like most of the other backends do, but they don't seem to be consistent.  Also why 'g', why not 'G', or 'GiB' or 'GB' or all of the above?  If we want to have a *standard* we should in fact have it be standard and we should parse out these standard things like size in a common way using a common method that handles all of them.

**Comment by adkerr** [comment]
Internally tracked by [US2206](https://rally1.rallydev.com/#/47479883219d/detail/userstory/90743220956)

**Comment by innergy** [comment]
Fixed in 17.04.0
