### ISSUE TITLE
Change NFS version to 4

### ISSUE THREAD

**Issue by paveljeloudovski** [NetApp/netappdvp#72]
I guess this is a feature request.
It seems the plugin uses NFS v3 hard-coded when using ontap-nas. 
Is there a way to tell the plugin to use NFS v4?

**Comment by adkerr** [comment]
Internally tracked by [US2279](https://rally1.rallydev.com/#/47479883219d/detail/userstory/93638594928)

**Comment by adkerr** [comment]
Addressed in commit 8b8fd67

**Comment by paveljeloudovski** [comment]
Awesome! Thanks.
