### ISSUE TITLE
Export policy for ontap-nas storage driver

### ISSUE THREAD

**Issue by franc01s** [NetApp/netappdvp#75]
Is there a way to configure which export policy I want to use in case of nas storage driver ?
I remarked that "default" is used and I have to add docker host to it for it works.
Any help appreciated.

**Comment by adkerr** [comment]
I believe you can set it in the config.json file using

```exportPolicy=<name>```

Or during the container launch with

```-o exportPolicy=<name>```

**Comment by franc01s** [comment]
It works by setting -o exportPolicy during volume creation process 
`docker volume create -d store/netapp/ndvp-plugin:1.4.0    --name=test -o size=10g  -o exportPolicy=docker`

Thanks a lot
