### ISSUE TITLE
Multiple IPs or FQDN in dataLIF configuration entry

### ISSUE THREAD

**Issue by plz** [NetApp/netappdvp#78]
Hi Team,

Not sure if this is a dupe of #77 but in our environment we use roundrobin dns entries for our NFS svm with data lifs living in multiple nodes. And then when client mounts the rr-dns takes care of some level of distribution of traffic from multiple clients to these various lifs.

Currently the [dataLIF](http://netappdvp.readthedocs.io/en/latest/install/ndvp_ontap_config.html) only accepts one IP, not allowing us to replicate this behavior in our k8s/trident/ndvp environment.

Are there plans to extend this configuration directive?

Thanks

**Comment by adkerr** [comment]
@plz,

I think this is a different issue than #77. You are looking for load balancing around data lifs on a single cluster, so a single management interface but multiple data interfaces. In the other issue they are wanting HA between multiple clusters, so multiple management interfaces with failover detection.

I have added this RFE to our tracking system as [US2444](https://rally1.rallydev.com/#/47479883219d/detail/userstory/114065429784)

**Comment by adkerr** [comment]
Resolved in commit 9ae43a655cc4b4e52d2dd4f9b321f37aa510f154 and available via Trident for Docker v18.01
