### ISSUE TITLE
plugin failed with error: rpc error: code = 2 desc = containerd: container not found

### ISSUE THREAD

**Issue by manojchaudhari76** [NetApp/netappdvp#79]
Hello,

I am trying to use netapp volume plugin...but i fail to enable the plugin...here is the reference doc followed...for NFS : http://netappdvp.readthedocs.io/en/latest/quick_start.html

I wondering if I am doing it right...appreciate help !
-----------------------------------------------------------------------------------------------
Prerequisites are taken care. Installed Packages :
nfs-utils.x86_64 1:1.3.0-0.8.el7 @anaconda/7.1

-----------------------------------------------------------------------------------------------
**$ docker plugin ls**
ID NAME DESCRIPTION ENABLED
2b4cdda1ce40 netapp:latest nDVP - NetApp Docker Volume Plugin false

-----------------------------------------------------------------------------------------------
**config.json :**
cat /etc/netappdvp/config.json
{
"version": 1,
"storageDriverName": "ontap-nas",
"managementLIF": "10.0.0.1",
"dataLIF": "10.0.0.2",
"svm": "svm_nfs",
"username": "vsadmin",
"password": "netapp123",
"aggregate": "aggr1",
"defaults": {
"size": "10G",
"spaceReserve": "none",
"exportPolicy": "default"
}
}

-----------------------------------------------------------------------------------------------

**$ docker info**
Containers: 1
Running: 0
Paused: 0
Stopped: 1
Images: 48
Server Version: 17.04.0-ce
Storage Driver: devicemapper
Pool Name: docker-8:3-975052-pool
Pool Blocksize: 65.54kB
Base Device Size: 10.74GB
Backing Filesystem: xfs
Data file: /dev/loop0
Metadata file: /dev/loop1
Data Space Used: 6.822GB
Data Space Total: 107.4GB
Data Space Available: 19.02GB
Metadata Space Used: 7.414MB
Metadata Space Total: 2.147GB
Metadata Space Available: 2.14GB
Thin Pool Minimum Free Space: 10.74GB
Udev Sync Supported: true
Deferred Removal Enabled: false
Deferred Deletion Enabled: false
Deferred Deleted Device Count: 0
Data loop file: /var/lib/docker/devicemapper/devicemapper/data
Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
Library Version: 1.02.107-RHEL7 (2015-10-14)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
Volume: local
Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary:
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
seccomp
Profile: default
Kernel Version: 3.10.0-229.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.1 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 15.52GiB
Name: 
ID: 66N4:EYHZ:ANVU:ZHYG:Z7SM:EHHW:B2NK:3ENQ:TX72:ITQG:7IWA:RXX5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
Use --storage-opt dm.thinpooldev to specify a custom block storage device.
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
-----------------------------------------------------------------------------------------------
**Command : docker plugin enable netapp

Error in /var/log/messages :**

40051 May 9 15:48:11 dockerd: time="2017-05-09T15:48:11+05:30" level=info msg="Running: /netapp/netappdvp --debug=false --config=/etc/netappdvp/config.json" plugin=2b4cdda1ce40c484ee6a04b5f60b47a2e77730b59133694af5d7acd8a0493c16
40052 May 9 15:48:11 dockerd: time="2017-05-09T15:48:11+05:30" level=info msg="time="2017-05-09T10:18:11Z" level=info msg="Initialized logging." logFileLocation="/var/log/netappdvp/netapp.log" logLevel=info " plugin=2b4cdda1ce40c484ee6a04b5f60b47a2e77730b59133694af5d7acd8a0493c16
40053 May 9 15:48:11 dockerd: time="2017-05-09T15:48:11+05:30" level=info msg="panic: Post https://10.0.0.1/servlets/netapp.servlets.admin.XMLrequest_filer: dial tcp 10.0.0.1:443: getsockopt: no route to host" plugin=2b4cdda1ce40c484ee6a04b5f60b47a2e77730b59133694af5d7acd8a0493c16
40054 May 9 15:48:11 dockerd: time="2017-05-09T15:48:11+05:30" level=info plugin=2b4cdda1ce40c484ee6a04b5f60b47a2e77730b59133694af5d7acd8a0493c16
40055 May 9 15:48:11 dockerd: time="2017-05-09T15:48:11+05:30" level=info msg="goroutine 1 [running]:" plugin=2b4cdda1ce40c484ee6a04b5f60b47a2e77730b59133694af5d7acd8a0493c16
40056 May 9 15:48:11 dockerd: time="2017-05-09T15:48:11+05:30" level=info msg="panic(0x957c20, 0xc8200fc000)" plugin=2b4cdda1ce40c484ee6a04b5f60b47a2e77730b59133694af5d7acd8a0493c16
40057 May 9 15:48:11 dockerd: time="2017-05-09T15:48:11+05:30" level=info msg="\t/usr/local/go/src/runtime/panic.go:481 +0x3e6" plugin=2b4cdda1ce40c484ee6a04b5f60b47a2e77730b59133694af5d7acd8a0493c16
40058 May 9 15:48:11 dockerd: time="2017-05-09T15:48:11+05:30" level=info msg="github.com/netapp/netappdvp/azgo.(*ZapiRunner).SendZapi(0xc820058240, 0x7fe4d7d2cc18, 0xc8200b4d20, 0x7fe4d7d2cc18, 0x0, 0x0)" plugin=2b4cdda1ce40c484ee6a04b5f60b47a2e77730b59133694af5d7acd8a0493c16
40059 May 9 15:48:11 dockerd: time="2017-05-09T15:48:11+05:30" level=info msg="\t/go/src/github.com/netapp/netappdvp/azgo/common.go:66 +0x88d" plugin=2b4cdda1ce40c484ee6a04b5f60b47a2e77730b59133694af5d7acd8a0493c16
40060 May 9 15:48:11 dockerd: time="2017-05-09T15:48:11+05:30" level=info msg="github.com/netapp/netappdvp/azgo.(*SystemGetOntapiVersionRequest).ExecuteUsing(0xc8200b4d20, 0xc820058240, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)" plugin=2b4cdda1ce40c484ee6a04b5f60b47a2e77730b59133694af5d7acd8a0493c16
40061 May 9 15:48:11 dockerd: time="2017-05-09T15:48:11+05:30" level=info msg="\t/go/src/github.com/netapp/netappdvp/azgo/system-get-ontapi-version.go:31 +0x99" plugin=2b4cdda1ce40c484ee6a04b5f60b47a2e77730b59133694af5d7acd8a0493c16
40062 May 9 15:48:11 dockerd: time="2017-05-09T15:48:11+05:30" level=info msg="github.com/netapp/netappdvp/apis/ontap.Driver.SystemGetOntapiVersion(0xc8200116e0, 0x8, 0xc8200116f0, 0x7, 0xc8200116f7, 0x7, 0xc820011700, 0x9, 0xc820058240, 0xc820011818, ...)" plugin=2b4cdda1ce40c484ee6a04b5f60b47a2e77730b59133694af5d7acd8a0493c16
40063 May 9 15:48:11 dockerd: time="2017-05-09T15:48:11+05:30" level=info msg="\t/go/src/github.com/netapp/netappdvp/apis/ontap/ontap.go:515 +0x98" plugin=2b4cdda1ce40c484ee6a04b5f60b47a2e77730b59133694af5d7acd8a0493c16
40064 May 9 15:48:11 dockerd: time="2017-05-09T15:48:11+05:30" level=info msg="github.com/netapp/netappdvp/storage_drivers.InitializeOntapDriver(0x1, 0xc8200116d1, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)" plugin=2b4cdda1ce40c484ee6a04b5f60b47a2e77730b59133694af5d7acd8a0493c16
40065 May 9 15:48:11 dockerd: time="2017-05-09T15:48:11+05:30" level=info msg="\t/go/src/github.com/netapp/netappdvp/storage_drivers/ontap_common.go:32 +0x3e5" plugin=2b4cdda1ce40c484ee6a04b5f60b47a2e77730b59133694af5d7acd8a0493c16
40066 May 9 15:48:11 dockerd: time="2017-05-09T15:48:11+05:30" level=info msg="github.com/netapp/netappdvp/storage_drivers.(*OntapNASStorageDriver).Initialize(0xc820074840, 0xc820074f20, 0x14b, 0x0, 0x0)" plugin=2b4cdda1ce40c484ee6a04b5f60b47a2e77730b59133694af5d7acd8a0493c16
40067 May 9 15:48:11 dockerd: time="2017-05-09T15:48:11+05:30" level=info msg="\t/go/src/github.com/netapp/netappdvp/storage_drivers/ontap_nas.go:71 +0x723" plugin=2b4cdda1ce40c484ee6a04b5f60b47a2e77730b59133694af5d7acd8a0493c16
40068 May 9 15:48:11 dockerd: time="2017-05-09T15:48:11+05:30" level=info msg="main.main()" plugin=2b4cdda1ce40c484ee6a04b5f60b47a2e77730b59133694af5d7acd8a0493c16
40069 May 9 15:48:11 dockerd: time="2017-05-09T15:48:11+05:30" level=info msg="\t/go/src/github.com/netapp/netappdvp/main.go:78 +0xcdc" plugin=2b4cdda1ce40c484ee6a04b5f60b47a2e77730b59133694af5d7acd8a0493c16
40070 May 9 15:48:11 dockerd: time="2017-05-09T15:48:11+05:30" level=info msg="Running: /netapp/netappdvp --debug=false --config=/etc/netappdvp/config.json" plugin=2b4cdda1ce40c484ee6a04b5f60b47a2e77730b59133694af5d7acd8a0493c16
40071 May 9 15:48:11 dockerd: time="2017-05-09T15:48:11+05:30" level=info msg="time="2017-05-09T10:18:11Z" level=info msg="Initialized logging." logFileLocation="/var/log/netappdvp/netapp.log" logLevel=info " plugin=2b4cdda1ce40c484ee6a04b5f60b47a2e77730b59133694af5d7acd8a0493c16
40072 May 9 15:48:11 dockerd: time="2017-05-09T15:48:11+05:30" level=info msg="panic: Post https://10.0.0.1/servlets/netapp.servlets.admin.XMLrequest_filer: dial tcp 10.0.0.1:443: getsockopt: no route to host" plugin=2b4cdda1ce40c484ee6a04b5f60b47a2e77730b59133694af5d7acd8a0493c16
40073 May 9 15:48:11 dockerd: time="2017-05-09T15:48:11+05:30" level=info plugin=2b4cdda1ce40c484ee6a04b5f60b47a2e77730b59133694af5d7acd8a0493c16
40074 May 9 15:48:11 dockerd: time="2017-05-09T15:48:11+05:30" level=info msg="goroutine 1 [running]:" plugin=2b4cdda1ce40c484ee6a04b5f60b47a2e77730b59133694af5d7acd8a0493c16
40075 May 9 15:48:11 dockerd: time="2017-05-09T15:48:11+05:30" level=info msg="panic(0x957c20, 0xc8200fe000)" plugin=2b4cdda1ce40c484ee6a04b5f60b47a2e77730b59133694af5d7acd8a0493c16
40076 May 9 15:48:11 dockerd: time="2017-05-09T15:48:11+05:30" level=info msg="\t/usr/local/go/src/runtime/panic.go:481 +0x3e6" plugin=2b4cdda1ce40c484ee6a04b5f60b47a2e77730b59133694af5d7acd8a0493c16
40077 May 9 15:48:11 dockerd: time="2017-05-09T15:48:11+05:30" level=info msg="github.com/netapp/netappdvp/azgo.(*ZapiRunner).SendZapi(0xc820058240, 0x7ffef30fcc18, 0xc8200b4d20, 0x7ffef30fcc18, 0x0, 0x0)" plugin=2b4cdda1ce40c484ee6a04b5f60b47a2e77730b59133694af5d7acd8a0493c16
40078 May 9 15:48:11 dockerd: time="2017-05-09T15:48:11+05:30" level=info msg="\t/go/src/github.com/netapp/netappdvp/azgo/common.go:66 +0x88d" plugin=2b4cdda1ce40c484ee6a04b5f60b47a2e77730b59133694af5d7acd8a0493c16
40079 May 9 15:48:11 dockerd: time="2017-05-09T15:48:11+05:30" level=info msg="github.com/netapp/netappdvp/azgo.(*SystemGetOntapiVersionRequest).ExecuteUsing(0xc8200b4d20, 0xc820058240, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)" plugin=2b4cdda1ce40c484ee6a04b5f60b47a2e77730b59133694af5d7acd8a0493c16
40080 May 9 15:48:11 dockerd: time="2017-05-09T15:48:11+05:30" level=info msg="\t/go/src/github.com/netapp/netappdvp/azgo/system-get-ontapi-version.go:31 +0x99" plugin=2b4cdda1ce40c484ee6a04b5f60b47a2e77730b59133694af5d7acd8a0493c16
40081 May 9 15:48:11 dockerd: time="2017-05-09T15:48:11+05:30" level=info msg="github.com/netapp/netappdvp/apis/ontap.Driver.SystemGetOntapiVersion(0xc8200116e0, 0x8, 0xc8200116f0, 0x7, 0xc8200116f7, 0x7, 0xc820011700, 0x9, 0xc820058240, 0xc820011818, ...)" plugin=2b4cdda1ce40c484ee6a04b5f60b47a2e77730b59133694af5d7acd8a0493c16
40082 May 9 15:48:11 dockerd: time="2017-05-09T15:48:11+05:30" level=info msg="\t/go/src/github.com/netapp/netappdvp/apis/ontap/ontap.go:515 +0x98" plugin=2b4cdda1ce40c484ee6a04b5f60b47a2e77730b59133694af5d7acd8a0493c16
40083 May 9 15:48:11 dockerd: time="2017-05-09T15:48:11+05:30" level=info msg="github.com/netapp/netappdvp/storage_drivers.InitializeOntapDriver(0x1, 0xc8200116d1, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)" plugin=2b4cdda1ce40c484ee6a04b5f60b47a2e77730b59133694af5d7acd8a0493c16
40084 May 9 15:48:11 dockerd: time="2017-05-09T15:48:11+05:30" level=info msg="\t/go/src/github.com/netapp/netappdvp/storage_drivers/ontap_common.go:32 +0x3e5" plugin=2b4cdda1ce40c484ee6a04b5f60b47a2e77730b59133694af5d7acd8a0493c16
40085 May 9 15:48:11 dockerd: time="2017-05-09T15:48:11+05:30" level=info msg="github.com/netapp/netappdvp/storage_drivers.(*OntapNASStorageDriver).Initialize(0xc820074840, 0xc820074f20, 0x14b, 0x0, 0x0)" plugin=2b4cdda1ce40c484ee6a04b5f60b47a2e77730b59133694af5d7acd8a0493c16
40086 May 9 15:48:11 dockerd: time="2017-05-09T15:48:11+05:30" level=info msg="\t/go/src/github.com/netapp/netappdvp/storage_drivers/ontap_nas.go:71 +0x723" plugin=2b4cdda1ce40c484ee6a04b5f60b47a2e77730b59133694af5d7acd8a0493c16
40087 May 9 15:48:11 dockerd: time="2017-05-09T15:48:11+05:30" level=info msg="main.main()" plugin=2b4cdda1ce40c484ee6a04b5f60b47a2e77730b59133694af5d7acd8a0493c16
40088 May 9 15:48:11 dockerd: time="2017-05-09T15:48:11+05:30" level=info msg="\t/go/src/github.com/netapp/netappdvp/main.go:78 +0xcdc" plugin=2b4cdda1ce40c484ee6a04b5f60b47a2e77730b59133694af5d7acd8a0493c16
**40089 May 9 15:48:23 dockerd: time="2017-05-09T15:48:23.690310777+05:30" level=error msg="Sending SIGTERM to plugin failed with error: rpc error: code = 2 desc = containerd: container not found"
40090 May 9 15:48:23 dockerd: time="2017-05-09T15:48:23.796122676+05:30" level=error msg="Sending SIGTERM to plugin failed with error: rpc error: code = 2 desc = containerd: container not found"**

**Comment by adkerr** [comment]
@manojchaudhari76 

It looks like a networking error:

>40053 May 9 15:48:11 dockerd: time="2017-05-09T15:48:11+05:30" level=info msg="panic: Post https://10.0.0.1/servlets/netapp.servlets.admin.XMLrequest_filer: dial tcp 10.0.0.1:443: getsockopt: no route to host" plugin=2b4cdda1ce40c484ee6a04b5f60b47a2e77730b59133694af5d7acd8a0493c16

Are you able to ping 10.0.0.1?

**Comment by manojchaudhari76** [comment]
I guess it is not...I am running it on a VM....

ping 10.0.0.1
PING 10.0.0.1 (10.0.0.1) 56(84) bytes of data.
From 172.30.0.1 icmp_seq=1 Time to live exceeded

**Comment by adkerr** [comment]
You'll need to resolve the networking problem then. The plugin is attempting to contact the server for some initial verification steps and when that fails it terminates, thus the container that containerd is looking for is missing.

Once you're able to successfully ping your filer it think the `docker plugin enable netapp` command should work fine.

**Comment by manojchaudhari76** [comment]
Sure...let me get some more help from my IT. Thanks to point out this...
