### ISSUE TITLE
RFE: Specify the default min/max/burst IOPS with the SolidFire driver

### ISSUE THREAD

**Issue by acsulli** [NetApp/netappdvp#8]
When creating a volume using the SolidFire driver, and no type is specified during the create process, the SolidFire array will create the volume with a default QoS policy of minimum 50 IOPS, max 15000 IOPS, and burst of 15000 IOPS.  It would be better if default values could be specified in the driver config file during startup.

Andrew

**Comment by j-griffith** [comment]
Yeah, that's a reasonable idea for sure.  I'll have a look at introducing parsing of a default type

**Comment by adkerr** [comment]
Internally tracked by [US2171](https://rally1.rallydev.com/#/47479883219d/detail/userstory/86711967832)

**Comment by adkerr** [comment]
Moved to netapp/trident#78
