### ISSUE TITLE
nDVP plugin requires /etc/iscsi bind mount even for NFS only installs

### ISSUE THREAD

**Issue by adkerr** [NetApp/netappdvp#82]
In order to install nDVP as a Docker managed plugin the user is required to have a directory `/etc/iscsi` even if they only intend to use NFS connections.  Users in this case may not have `/etc/iscsi` and as a work-around must create an empty directory.

**Comment by dsmorse** [comment]
until this is fixed, it should be documented http://netappdvp.readthedocs.io/en/latest/install/host_config.html#docker-managed-plugin-method-docker-1-13-17-03 this PR is the only thing that got me past the /etc./iscsi error
