### ISSUE TITLE
SolidFire volume creation from clone should allow setting of QoS

### ISSUE THREAD

**Issue by dutchiechris** [NetApp/netappdvp#85]
If you create a clone volume using `docker volume create --driver netapp --name volGoldClone -o from=volGold` the QoS settings are inherited/reused from the parent.  If you pass a specific option like `-o type=dev` this is ignored.  Especially when making dev/test clones of production a different QoS limit is desired.  If nDVP would allow specifying QoS settings to clones it would avoid other external post scripts that are currently needed.

**Comment by j-griffith** [comment]
Thanks dutchiechris, pretty easy to add in; I'll get it pushed internally and it should pop out in the next release.
