### ISSUE TITLE
Create volume error

### ISSUE THREAD

**Issue by Astomat** [NetApp/netappdvp#87]
Hello,
When I try to create a volume on e-series, I receive the following error:
sudo docker volume create -d netapp --name firstVolume
Error response from daemon: create firstVolume: VolumeDriver.Create: Error creating volume: Could not create volume netappdvp_firstVolume. Could not create volume netappdvp_firstVolume. API failed. Status code: 422. Error: The operation cannot complete because you did not provide a valid administrator password. Localized: The operation cannot complete because you did not provide a valid administrator password.

What can be done? Where I set the administrator password.
The proxy version is 2.1.

Thanks.

**Comment by adkerr** [comment]
Hi @Astomat,

The administrator password is set in the config.json file:

```json
{    
    "version": 1,    
    "storageDriverName": "eseries-iscsi",    
    "debug": true,    
    "webProxyHostname": "10.0.0.1",    
    "webProxyPort": "8444",
    "webProxyUseHTTP": true,
    "webProxyVerifyTLS": false,
    "username": "rw",    
    "password": "rw",    
    "controllerA": "10.0.0.2",    
    "controllerB": "10.0.0.3",    
    "passwordArray": "secret", <==== administrator password for ESeries array    
    "hostData_IP": "10.0.1.1",
    "debugTraceFlags": {"method": true, "api": true}
}
```

**Comment by Astomat** [comment]
The password is configured and it is correct.
I have checked it many times.
Maybe somthing special is needed to configured on the NetApp itself?

**Comment by korenaren** [comment]
Did you ever figure this out? Sorry for lack of response. Let me know if you still see this problem.
