### ISSUE TITLE
(Docs) Example for specifying the config option with the file name

### ISSUE THREAD

**Issue by scaleoutsean** [NetApp/netappdvp#95]
From the [doc](https://netappdvp.readthedocs.io/en/latest/install/host_config.html#docker-managed-plugin-method-docker-1-13-17-03) "Installing the Managed Plugin"
`Create a configuration file. The config file must be located in the /etc/netappdvp directory. The default filename is config.json, however you can use any name you choose by specifying the config option with the file name.`

Can someone clarify how this config option with the file name is set and where? It's unclear from the context.

**Comment by ntap-rippy** [comment]
We'll need to update the doc, but until we can do that, hopefully this will help.

$ docker plugin install --help
Usage:	docker plugin install [OPTIONS] PLUGIN [KEY=VALUE...]

$ docker plugin install --grant-all-permissions --alias netapp netapp/ndvp-plugin:17.07 config=myOtherConfig.json

Relevant implementation snippet in [container-launch.sh](https://github.com/NetApp/netappdvp/blob/master/contrib/docker/plugin/container-launch.sh#L15-L18)

Can 'plugin set' it too:
$ docker plugin set --help
Usage:	docker plugin set PLUGIN KEY=VALUE [KEY=VALUE...]
